<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
	<NuGetAuditSuppress>true</NuGetAuditSuppress>
	<NuGetAudit>false</NuGetAudit>
    <Nullable>enable</Nullable>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <StartupObject>AITSYS.RpgMakerMv.MapInfos.MapInfoGenerator</StartupObject>
  </PropertyGroup>


  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
	<NoWarn>1701;1702;NU1701;NU5104;CS2019;NU1605;DCS0102</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
	<NoWarn>1701;1702;NU1701;NU5104;CS2019;NU1605;DCS0102</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Newtonsoft.Json" />
  </ItemGroup>

</Project>
