name: "Release RPC"

on:
  workflow_dispatch:
    inputs:
      build_description:
        description: 'Build description'
        required: true
        default: 'No information given'
        type: string
      build_version:
        description: 'Build version'
        required: true
        type: string
      upload_to_steam:
        description: 'Upload to Steam'
        required: true
        default: false
        type: boolean

permissions: write-all

jobs:
  release:
    name: Release RPC V${{ inputs.build_version }}
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: "Setup .NET"
        uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6
        with:
            dotnet-version: 10.x
      - name: "Restore & build project"
        run: |
          dotnet build -c Release ./src/AITSYS.RpgMakerMv.Rpc/AITSYS.RpgMakerMv.Rpc.csproj
      - name: "Publish project"
        run: |
          dotnet publish -r win-x64 --self-contained=true -p:PublishSingleFile=true -p:GenerateRuntimeConfigurationFiles=false -c Release -o "./dist/RPC Plugin" ./src/AITSYS.RpgMakerMv.Rpc/AITSYS.RpgMakerMv.Rpc.csproj
          dotnet publish -r linux-x64 --self-contained=true -p:PublishSingleFile=true -p:GenerateRuntimeConfigurationFiles=false -c Release -o "./dist/RPC Plugin" ./src/AITSYS.RpgMakerMv.Rpc/AITSYS.RpgMakerMv.Rpc.csproj
      - name: "Generate TOTP"
        if: ${{ inputs.upload_to_steam }}
        uses: CyberAndrii/steam-totp@1661caebf0a84a79be0166020f81837039137101 # v1.2.0
        id: steam-totp
        with:
          shared_secret: ${{ secrets.STEAM_PARTNER_SHARED_SECRET }}
      - name: "Deploy to Steam"
        uses: game-ci/steam-deploy@50f6b29fc64922e19a16d202a88fe199d394b536 # v3.2.1
        if: ${{ inputs.upload_to_steam }}
        id: actual_steam_deploy
        with:
          username: ${{ secrets.STEAM_PARTNER_USERNAME }}
          password: ${{ secrets.STEAM_PARTNER_PASSWORD }}
          configVdf: ${{ secrets.STEAM_PARTNER_CONFIG_VDF }}
          totp: ${{ steps.steam-totp.outputs.code }}
          appId: 2184270
          buildDescription: v${{ inputs.build_version }} - ${{ inputs.build_description }}
          rootPath: ./
          firstDepotIdOverride: 2184300
          depot1Path: dist
          releaseBranch: "develop"
      - name: "Create GitHub Release"
        uses: softprops/action-gh-release@efb35369e0ad2afab669f228072c1b0d510eae64 # v3.0.3
        with:
          body: RMMV RPC Release - ${{ inputs.build_description }}
          tag_name: rmmv-rpc-v${{ inputs.build_version }}
          name: RMMV Discord RPC v${{ inputs.build_version }}
          prerelease: true
          generate_release_notes: true
          files: |
            ./dist/RPC Plugin/AITSYS.RpgMakerMv.Rpc
            ./dist/RPC Plugin/AITSYS.RpgMakerMv.Rpc.exe
            ./src/AITSYS_RPC-min.js
            ./static/README-RPC.txt
